[2021-06-09 13:43:55,554: INFO/MainProcess] Connected to redis://redis:6379/0
[2021-06-09 13:43:55,562: INFO/MainProcess] mingle: searching for neighbors
[2021-06-09 13:43:56,584: INFO/MainProcess] mingle: all alone
[2021-06-09 13:43:56,598: INFO/MainProcess] celery@d27561219911 ready.
[2021-06-09 13:45:48,094: INFO/MainProcess] Connected to redis://redis:6379/0
[2021-06-09 13:45:48,102: INFO/MainProcess] mingle: searching for neighbors
[2021-06-09 13:45:49,122: INFO/MainProcess] mingle: all alone
[2021-06-09 13:45:49,141: INFO/MainProcess] celery@7577d6eb92d0 ready.
[2021-06-09 13:46:49,131: INFO/MainProcess] Connected to redis://redis:6379/0
[2021-06-09 13:46:49,143: INFO/MainProcess] mingle: searching for neighbors
[2021-06-09 13:46:50,164: INFO/MainProcess] mingle: all alone
[2021-06-09 13:46:50,180: INFO/MainProcess] celery@2bd0e2be2b6a ready.
[2021-06-09 13:47:09,608: INFO/MainProcess] Received task: create_task[9fb29383-31e2-40a8-90f7-51536d194e07]  
[2021-06-09 13:47:09,654: ERROR/ForkPoolWorker-3] Task create_task[9fb29383-31e2-40a8-90f7-51536d194e07] raised unexpected: OperationalError('(sqlite3.OperationalError) no such table: matches')
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1770, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 717, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such table: matches

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 412, in trace_task
    R = retval = fun(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/celery/app/trace.py", line 704, in __protected_call__
    return self.run(*args, **kwargs)
  File "/usr/src/app/project/server/tasks.py", line 39, in create_task
    match = Matche.query.get(match_id)
  File "<string>", line 2, in get
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/deprecations.py", line 390, in warned
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 933, in get
    return self._get_impl(ident, loading.load_on_pk_identity)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 937, in _get_impl
    return self.session._get_impl(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 2827, in _get_impl
    return db_load_fn(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/loading.py", line 531, in load_on_pk_identity
    session.execute(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1677, in execute
    result = conn._execute_20(statement, params or {}, execution_options)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1582, in _execute_20
    return meth(self, args_10style, kwargs_10style, execution_options)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 324, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1451, in _execute_clauseelement
    ret = self._execute_context(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1813, in _execute_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1994, in _handle_dbapi_exception
    util.raise_(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 207, in raise_
    raise exception
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1770, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 717, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such table: matches
[SQL: SELECT matches.id AS matches_id, matches.tm0_defeats_h AS matches_tm0_defeats_h, matches.tm1_wins_h AS matches_tm1_wins_h, matches.tm2_defeats AS matches_tm2_defeats, matches."tm0_BTS_a" AS "matches_tm0_BTS_a", matches."tm2_GC_a" AS "matches_tm2_GC_a", matches."tm2_BoTS_h" AS "matches_tm2_BoTS_h", matches."tm1_BoTS_h" AS "matches_tm1_BoTS_h", matches.tm0_25 AS matches_tm0_25, matches."tm0_TGG_a" AS "matches_tm0_TGG_a", matches."tm2_WtN_h" AS "matches_tm2_WtN_h", matches."tm0_D_a" AS "matches_tm0_D_a", matches."tm0_GSG_h" AS "matches_tm0_GSG_h", matches."tm2_GCG_a" AS "matches_tm2_GCG_a", matches.tm2_25_a AS matches_tm2_25_a, matches."tm2_D" AS "matches_tm2_D", matches."tm2_ClS_h" AS "matches_tm2_ClS_h", matches.tm1_35_h AS matches_tm1_35_h, matches.tm0_defeats_a AS matches_tm0_defeats_a, matches.tm0_defeats AS matches_tm0_defeats, matches."tm0_TGG_h" AS "matches_tm0_TGG_h", matches."tm0_TGG" AS "matches_tm0_TGG", matches."tm0_BTS" AS "matches_tm0_BTS", matches."tm0_PPGH_h" AS "matches_tm0_PPGH_h", matches.tm1_defeats_h AS matches_tm1_defeats_h, matches.tm0_35 AS matches_tm0_35, matches."tm2_BTS" AS "matches_tm2_BTS", matches.tm0_35_a AS matches_tm0_35_a, matches."tm1_GCG_h" AS "matches_tm1_GCG_h", matches."tm2_FtS_h" AS "matches_tm2_FtS_h", matches.tm0_wins AS matches_tm0_wins, matches."tm1_GC_h" AS "matches_tm1_GC_h", matches."tm2_PPGA_a" AS "matches_tm2_PPGA_a", matches."tm1_TGG" AS "matches_tm1_TGG", matches."tm1_PPGH_h" AS "matches_tm1_PPGH_h", matches."tm1_GSG_h" AS "matches_tm1_GSG_h", matches."tm0_GS_h" AS "matches_tm0_GS_h", matches.tm1_35 AS matches_tm1_35, matches."tm1_SiBH_h" AS "matches_tm1_SiBH_h", matches."tm1_FtS_h" AS "matches_tm1_FtS_h", matches."tm2_TGG_a" AS "matches_tm2_TGG_a", matches."tm1_GSG" AS "matches_tm1_GSG", matches."tm1_GCG" AS "matches_tm1_GCG", matches."tm2_BTS_a" AS "matches_tm2_BTS_a", matches.tm2_wins_a AS matches_tm2_wins_a, matches.tm2_35_a AS matches_tm2_35_a, matches.tm1_points_h AS matches_tm1_points_h, matches.tm0_25_a AS matches_tm0_25_a, matches."tm1_CiBH_h" AS "matches_tm1_CiBH_h", matches."tm2_GS_a" AS "matches_tm2_GS_a", matches."tm1_WtN_h" AS "matches_tm1_WtN_h", matches.tm0_25_h AS matches_tm0_25_h, matches."tm1_D_h" AS "matches_tm1_D_h", matches."tm2_GCG" AS "matches_tm2_GCG", matches."tm1_GS_h" AS "matches_tm1_GS_h", matches."tm1_BTS" AS "matches_tm1_BTS", matches."tm0_GCG" AS "matches_tm0_GCG", matches."tm2_CiBH_h" AS "matches_tm2_CiBH_h", matches."tm0_PPGH" AS "matches_tm0_PPGH", matches.tm1_defeats AS matches_tm1_defeats, matches."tm2_D_a" AS "matches_tm2_D_a", matches."tm0_D" AS "matches_tm0_D", matches."tm1_TGG_h" AS "matches_tm1_TGG_h", matches."tm1_ClS_h" AS "matches_tm1_ClS_h", matches."tm0_D_h" AS "matches_tm0_D_h", matches.tm0_35_h AS matches_tm0_35_h, matches."tm2_GSG" AS "matches_tm2_GSG", matches."tm0_GS_a" AS "matches_tm0_GS_a", matches.tm0_wins_h AS matches_tm0_wins_h, matches."tm0_GCG_h" AS "matches_tm0_GCG_h", matches."tm1_D" AS "matches_tm1_D", matches."tm0_GCG_a" AS "matches_tm0_GCG_a", matches."tm0_GSG" AS "matches_tm0_GSG", matches."tm2_TGG" AS "matches_tm2_TGG", matches.tm1_25 AS matches_tm1_25, matches."tm2_GSG_a" AS "matches_tm2_GSG_a", matches.tm2_points_a AS matches_tm2_points_a, matches."tm1_BTS_h" AS "matches_tm1_BTS_h", matches."tm2_SiBH_h" AS "matches_tm2_SiBH_h", matches."tm1_LtN_h" AS "matches_tm1_LtN_h", matches.tm1_wins AS matches_tm1_wins, matches.tm2_wins AS matches_tm2_wins, matches.tm2_25 AS matches_tm2_25, matches."tm0_BTS_h" AS "matches_tm0_BTS_h", matches.tm2_35 AS matches_tm2_35, matches.tm0_wins_a AS matches_tm0_wins_a, matches.tm2_defeats_a AS matches_tm2_defeats_a, matches.tm1_25_h AS matches_tm1_25_h, matches."tm0_GSG_a" AS "matches_tm0_GSG_a", matches."tm0_PPGH_a" AS "matches_tm0_PPGH_a", matches."tm2_LtN_h" AS "matches_tm2_LtN_h", matches.tm2_names AS matches_tm2_names, matches.scores AS matches_scores, matches.dates AS matches_dates, matches.tm1_names AS matches_tm1_names 
FROM matches 
WHERE matches.id = ?]
[parameters: (5,)]
(Background on this error at: http://sqlalche.me/e/14/e3q8)
